cities/urls.py
from django.urls import path

from cities.views import *

urlpatterns = [
    # path('', home, name='home'),
    path('', CityListView.as_view(), name='home'),
    path('detail/<int:pk>/', CityDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', CityUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', CityDeleteView.as_view(), name='delete'),
    path('add/', CityCreateView.as_view(), name='create'),

]

travel/urls.py
from django.contrib import admin
from django.urls import path, include

from routes.views import home, find_routes, add_route, save_route, RouteListView, RouteDetailView, RouteDeleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cities/', include(('cities.urls', 'cities'))),
    path('trains/', include(('trains.urls', 'trains'))),
    path('accounts/', include(('accounts.urls', 'accounts'))),
    path('', home, name='home'),
    path('find_routes/', find_routes, name='find_routes'),
    path('add_route/', add_route, name='add_route'),
    path('save_route/', save_route, name='save_route'),
    path('list/', RouteListView.as_view(), name='list'),
    path('detail/<int:pk>/', RouteDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', RouteDeleteView.as_view(), name='delete'),
]

routes/models.py
from django.db import models

from cities.models import City


class Route(models.Model):
    name = models.CharField(max_length=50, unique=True,
                            verbose_name='Название маршрута')
    travel_times = models.PositiveSmallIntegerField(verbose_name='Общее время в пути')
    from_city = models.ForeignKey(City, on_delete=models.CASCADE,
                                  related_name='route_from_city_set',
                                  verbose_name='Из какого города'
                                  )
    to_city = models.ForeignKey('cities.City', on_delete=models.CASCADE,
                                related_name='route_to_city_set',
                                verbose_name='В какой город')
    trains = models.ManyToManyField('trains.Train', verbose_name='Список поездов')

    def __str__(self):
        return f'Маршрут {self.name} из города {self.from_city}'

    class Meta:
        verbose_name = 'Маршрут'
        verbose_name_plural = 'Маршруты'
        ordering = ['travel_times']

templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>{{name}}!</h1>

{% endblock %}

templates/base.html
{% url 'cities:home' as cities_home_url %}
{% url 'cities:create' as cities_create_url %}
{% url 'trains:home' as trains_home_url %}
{% url 'trains:create' as trains_create_url %}
{% url 'list' as route_list %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
      <!-- Select2 forms search -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
      <nav class="navbar navbar-expand-lg navbar-light container" style="background-color: #e3f2fd;">
      <a class= "navbar-brand" href="{% url 'home' %}">FindRoute</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item {% if request.path == cities_home_url %} active {% endif %}">
              <a class="nav-link" href="{% url 'cities:home'%}">Города</a>
            </li>
            <li class="nav-item {% if request.path == trains_home_url %} active {% endif %}">
              <a class="nav-link" href="{% url 'trains:home'%}">Поезда</a>
            </li>
            <li class="nav-item {% if request.path == route_list %} active {% endif %}">
              <a class="nav-link" href="{% url 'list' %}">Маршруты</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item dropdown {% if request.path == cities_create_url or request.path == route_detail %} active {% endif %}">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Добавить
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'cities:create' %}">Новый город</a>
                <a class="dropdown-item" href="{% url 'trains:create' %}">Новый поезд</a>
              </div>
            </li>
              {% else %}
              <li class="nav-item">
              <a class="nav-link disabled" href="">Добавить</a>
              </li>
              {% endif %}
            {% if user.is_authenticated %}
             <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}">Выйти</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">Войти</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">Регистрация</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
      <div class="container">
        <div class="row">
          <div class="col-md-8 mx-auto my-4">
              {% if messages %}
                  {% for message in messages %}
                      {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                          {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                      {% else %}
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                          {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                      {% endif %}
                   {% endfor %}
               {% endif %}
          </div>
        </div>
      </div>
    <div class="container">
      {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
    <script>
        $(document).ready(function() {
            $('.js-example-basic-single').select2();
            $('.js-example-basic-multiple').select2();
        });
    </script>
  </body>
</html>

templates/form.html
<div class="row">
    <div class="col-md-4">
        <form action="{{action}}" method="post"> {% csrf_token %}
            {{ form.as_p }}
        <button type="submit" class="btn btn-primary">{{ button }}</button>
        </form>
    </div>
</div>

templates/home.html
<!DOCTYPE html>
<html>

<head>
	<link rel="stylesheet" href="styles.css">
</head>

<body>

	<h1>Hello {{name}}!</h1>

</body>

</html>